name: Deploy Firebase Functions

on:
  push:
    branches:
      - main
    paths:
      - 'functions/**'
      - '.github/workflows/deploy-functions.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Firebase CLI
        run: npm install -g firebase-tools

      - name: Instalar dependencias de Functions
        run: |
          cd functions
          npm install

      - name: Crear credenciales
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > /tmp/sa.json

     - name: Deploy Cloud Functions
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=/tmp/sa.json
          firebase deploy --only functions --project romulo-fc --non-interactive
